version: "3.8"
services:
  mongo:
    image: mongo:4.4.6
    container_name: mongo
    hostname: mongo
    networks:
      - mongo-network
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - db_data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    networks:
      - mongo-network
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
    depends_on:
      - mongo
volumes:
  db_data:
networks:
  mongo-network:
    driver: bridge
