version: "3.3"

services:
  db:
    image: postgres:latest
    env_file: docker-compose.env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    restart: always
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  db_data:
